<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'PhabricatorFilesConfigOptions' => 'extensions/files/config/PhabricatorFilesConfigOptions.php',
    'PhabricatorRackspaceConfigOptions' => 'extensions/config/option/PhabricatorRackspaceConfigOptions.php',
    'PhabricatorRackspaceFileStorageEngine' => 'extensions/files/engine/PhabricatorRackspaceFileStorageEngine.php',
  ),
  'function' => array(),
  'xmap' => array(
    'PhabricatorFilesConfigOptions' => 'PhabricatorApplicationConfigOptions',
    'PhabricatorRackspaceConfigOptions' => 'PhabricatorApplicationConfigOptions',
    'PhabricatorRackspaceFileStorageEngine' => 'PhabricatorFileStorageEngine',
  ),
));
